### ISSUE TITLE
Баг с редактором поста в мобиле 

### ISSUE THREAD

**Issue by kulbergArt** [BDemetrix/BDemetrix.github.io#91]
В мобильном редакторе когда пишешь очень большую статью, происходит странное нечто: при каждом вводе символа страница проскролливается сам вверх вниз (туса сюда). Получается своего родя дёргание экрана.

Можно с этим что-то сделать? Баг в JS какой-то

https://smart-lab.ru/mobile/topic/add/

**Comment by BDemetrix** [comment]
Добавил правлило в css для `.add-post__textarea`:       
```scss
 // .add-post__textarea 
    &__textarea {
        min-height: calc(100vh - 438px);
        max-height: calc(100vh - 318px);  // для устранения бага
    }
```
